Implement the WaitExecution and CancelOperation
allada/turbo-cache pull request #177
Opened 2023-07-14 15:39 UTC by chrisstaite-menlo

These functions are used by Goma.

This also resolves the issue of holding on to abandoned queued jobs.

I probably could break this down into a few more PRs, but I'd likely break something along the way.

2023-07-14 16:28 UTC, chrisstaite-menlo commented
*[`cas/grpc_service/execution_server.rs` line 216 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KDlWCAgyn33vz2bCl:-N_KDlWCAgyn33vz2bCm:b-amfk3) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L216)):*
> ```XML
>     }
> 
>     async fn lookup_action<'a, Fut, F, G, R, S>(&'a self, operation: F, mut filter: G) -> Result<S, Status>
> ```

If you think it's better to copy this code into the below two methods rather than this abomination of generics, let me know.  However, I kinda just wanted to do it to see if I could...


<!-- Sent from Reviewable.io -->

2023-07-14 16:38 UTC, allada requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 166 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KEYeq50_o7KdBrFUv:-N_KEYeq50_o7KdBrFUw:b-g3kdhq) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L166)):*
> ```XML
>     }
> 
>     pub fn into_services(self) -> (Server<ExecutionServer>, OperationsServer<ExecutionServer>) {
> ```

At first I was thinking, this should be a separate service and not share with ExecutionServer. Then I was like... "Nah, it makes sense to put them together"... Then I started reading the API and now I think they should be separate.

ExecutionServer only serves execution requests. OperationServer is designed to serve other kinds of operations too like "WaitForWorkerToComeOnline" or "DrainAndShutdown".

Because of this and unlikely, but possible additional features, lets break this into it's own `grpc_service`. All our operations will happen on the scheduler anyway, so interacting should be easy, since the scheduler can be referenced in both services.


<!-- Sent from Reviewable.io -->

2023-07-14 16:42 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 224 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KGyWWAyv7wXz32lmn:-N_KGyWXAwpch7ThQKN-:b-cs7e8b) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L224)):*
> ```XML
>         // Very innefficient having to search through all instances, however
>         // the protobuf spec doesn't state that the instance_name can be
>         // retrieved from the path.
> ```

Actually it can be retrieved from the path if it matches as outlined here:
https://github.com/allada/turbo-cache/blob/master/proto/build/bazel/remote/execution/v2/remote_execution.proto#L124


<!-- Sent from Reviewable.io -->

2023-07-14 16:45 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 224 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KGyWWAyv7wXz32lmn:-N_KHW6pA2-OBtUJKBTD:b-l1m29g) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L224)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Actually it can be retrieved from the path if it matches as outlined here:
https://github.com/allada/turbo-cache/blob/master/proto/build/bazel/remote/execution/v2/remote_execution.proto#L124
</blockquote></details>

Wait, no... We choose the name, so we choose the filter. In our case we can require any kind of filter format we want.


<!-- Sent from Reviewable.io -->

2023-07-14 19:15 UTC, allada reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 216 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KoJsHEUR3iJzEWj4j:-N_KoJsHEUR3iJzEWj4k:bdzn1z8) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L216)):*
> ```XML
>     }
> 
>     async fn lookup_action<'a, Fut, F, G, R, S>(&'a self, operation: F, mut filter: G) -> Result<S, Status>
> ```

nit: Lets rename `filter_actions()` and add a `limit` argument. This will make it trivial to implement `ListOperations()` in the future.
___
*[`cas/grpc_service/execution_server.rs` line 225 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KoklO7J1zto8vFX9x:-N_KoklO7J1zto8vFX9y:btgn8pg) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L225)):*
> ```XML
>         // the protobuf spec doesn't state that the instance_name can be
>         // retrieved from the path.
>         self.instance_infos
> ```

nit: This is super confusing, the `Stream` api makes it hard to understand what is happening, can we expand this into a `while let Some(item) = stream.next().await {` ?


<!-- Sent from Reviewable.io -->

2023-07-14 20:39 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 6 unresolved discussions (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/177#-N_L7BVy4y8ebVUUbCYm:-N_L7BVy4y8ebVUUbCYn:b-s79yb2) (no related file):*

Give me some time on this, I'm going to hack up your branch to get a better feel for it. There's a lot going on and I want to see how it goes.

Right now I'm leaning towards the operation service being completely separate from the execution service. Requiring a configuration and all.

___


<!-- Sent from Reviewable.io -->

2023-07-15 04:50 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 166 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KEYeq50_o7KdBrFUv:-N_MsGgK8y9WDL7mD5v_:b-2p8ixr) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L166)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

At first I was thinking, this should be a separate service and not share with ExecutionServer. Then I was like... "Nah, it makes sense to put them together"... Then I started reading the API and now I think they should be separate.

ExecutionServer only serves execution requests. OperationServer is designed to serve other kinds of operations too like "WaitForWorkerToComeOnline" or "DrainAndShutdown".

Because of this and unlikely, but possible additional features, lets break this into it's own `grpc_service`. All our operations will happen on the scheduler anyway, so interacting should be easy, since the scheduler can be referenced in both services.
</blockquote></details>

Disregard. I experimented with this idea for a few hours and came to the conclusion we should not try to recycle `Operation` for anything but BRE required stuff. It is a decent interface, but tonic doesn't really support HTTP1 + json endpoints yet, it's close, but I did some testing with tonic-web and it didn't really work for what I wanted, since it just encodes everything to a proto and requires input as a proto.


<!-- Sent from Reviewable.io -->

2023-07-15 05:01 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 7 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/cas_main.rs` line 217 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_MsqTf10c0-4lLZBKO:-N_MsqTf10c0-4lLZBKP:ba6io91) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/cas_main.rs#L217)):*
> ```XML
>                     .map_or(Ok(None), |cfg| {
>                         ExecutionServer::new(&cfg, &action_schedulers, &store_manager).map(|v| {
>                             let (mut execution_service, mut operations_service) = v.into_services();
> ```

I tried really really hard to make this interface not suck. Well I couldn't figure out a way to abstract this out without making a new config, which is pointless for us.
___
*[`cas/grpc_service/execution_server.rs` line 241 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_MujwQ9kzEFBhq8Kp3:-N_MujwQ9kzEFBhq8Kp4:b7lyvoz) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L241)):*
> ```XML
>         let name = request.into_inner().name;
>         self.lookup_action(
>             |instance_info| instance_info.scheduler.find_existing_action(&name),
> ```

Since this file is the gateway to all things execution related, lets rewrite all output `Operation`s so it has the instance name as prefixed to the operation name. Then just lookup what scheduler it should be on here.


<!-- Sent from Reviewable.io -->

2023-07-15 05:07 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 8 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 237 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_MwNyr4HQ8dVbN4GaZ:-N_MwNyr4HQ8dVbN4Ga_:b-d5wmm9) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L237)):*
> ```XML
>     async fn inner_wait_execution(
>         &self,
>         request: Request<WaitExecutionRequest>,
> ```

nit: Lets just pass in name as a string here and then this function is 100% compatible with: `wait_operation()`.


<!-- Sent from Reviewable.io -->

2023-07-15 05:14 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 308 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_MwaUY8wmhDBsNpR8d:-N_MwaUY8wmhDBsNpR8e:b-w2q467) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L308)):*
> ```XML
>     }
> 
>     async fn cancel_operation(&self, request: Request<CancelOperationRequest>) -> Result<Response<()>, Status> {
> ```

I'm really struggling on this one. Do we need/want to implement `cancel_operation`? I understand removing `delete_operation`, since it allows the scheduler to stop the action if it wants. But from what I can tell in the documentation, `cancel_operation` pretty much says: "Kill it, don't ask questions" and gives little flexibility.

The reason I'm worried here is because the scheduler multiplexes the actions. Meaning if two requests from two different clients come in for the same action, it will only execute the action one time and send the results to both clients. If we implement `cancel_action` we are allowing any client to terminate another client's action.

If the argument is made to say that's an implementation detail and the client should not be able to see other client's jobs and it should only terminate the job if no-one else is waiting on that job, I feel that's more of what `DeleteOperation` is for. But then again `DeleteOperation` might be more about actions that change external state (like upload files, install new software, exc...), which is why the client would not care about the results.


<!-- Sent from Reviewable.io -->

2023-07-15 11:46 UTC, chrisstaite-menlo commented
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>


Give me some time on this, I'm going to hack up your branch to get a better feel for it. There's a lot going on and I want to see how it goes.

Right now I'm leaning towards the operation service being completely separate from the execution service. Requiring a configuration and all.
</blockquote></details>

I think I'm going to drop the operations service.  It was mostly for the use case that someone changes a header that's used in a lot of files and it's bad, so cancels the build job but we still execute a bunch of jobs that are going to fail.  However, I don't think it really gains us all that much, so I think I'm going to drop it and we can bring it in a separate branch later if we want to.




<!-- Sent from Reviewable.io -->

2023-07-15 12:01 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @allada)

___
*[`cas/grpc_service/execution_server.rs` line 224 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KGyWWAyv7wXz32lmn:-N_OPSXd6_-lX0DmRLSx:b-3ktop1) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L224)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Wait, no... We choose the name, so we choose the filter. In our case we can require any kind of filter format we want.
</blockquote></details>

Think that falls down with the GrpcScheduler, right?
___
*[`cas/grpc_service/execution_server.rs` line 237 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_MwNyr4HQ8dVbN4GaZ:-N_OQCUPCnok4proxL2Z:b-9jrwbo) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L237)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets just pass in name as a string here and then this function is 100% compatible with: `wait_operation()`.
</blockquote></details>

Got rid of operation server, so probably not worth doing.
___
*[`cas/grpc_service/execution_server.rs` line 241 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_MujwQ9kzEFBhq8Kp3:-N_OQJ8gCEW2TBxben4y:biiifc3) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L241)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Since this file is the gateway to all things execution related, lets rewrite all output `Operation`s so it has the instance name as prefixed to the operation name. Then just lookup what scheduler it should be on here.
</blockquote></details>

Got rid of the operations server...
___
*[`cas/grpc_service/execution_server.rs` line 308 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_MwaUY8wmhDBsNpR8d:-N_OQMXc50VNCr-KrN2K:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L308)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm really struggling on this one. Do we need/want to implement `cancel_operation`? I understand removing `delete_operation`, since it allows the scheduler to stop the action if it wants. But from what I can tell in the documentation, `cancel_operation` pretty much says: "Kill it, don't ask questions" and gives little flexibility.

The reason I'm worried here is because the scheduler multiplexes the actions. Meaning if two requests from two different clients come in for the same action, it will only execute the action one time and send the results to both clients. If we implement `cancel_action` we are allowing any client to terminate another client's action.

If the argument is made to say that's an implementation detail and the client should not be able to see other client's jobs and it should only terminate the job if no-one else is waiting on that job, I feel that's more of what `DeleteOperation` is for. But then again `DeleteOperation` might be more about actions that change external state (like upload files, install new software, exc...), which is why the client would not care about the results.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-15 13:32 UTC, allada requested changes
> Reviewed 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 9 files reviewed, 6 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/allada/turbo-cache/177#-N_Ok46bBqDJO55yU_t2):*
I think something went wrong in your rebase.


<!-- Sent from Reviewable.io -->

2023-07-15 19:22 UTC, chrisstaite-menlo commented
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/allada/turbo-cache/177#-N_Ok46bBqDJO55yU_t2):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think something went wrong in your rebase.
</blockquote></details>

Whoops....


<!-- Sent from Reviewable.io -->

2023-07-15 21:04 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/177#-N_L7BVy4y8ebVUUbCYm:-N_QLucEDlzUIu_YD7X0:b-i7yh46) (no related file):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I think I'm going to drop the operations service.  It was mostly for the use case that someone changes a header that's used in a lot of files and it's bad, so cancels the build job but we still execute a bunch of jobs that are going to fail.  However, I don't think it really gains us all that much, so I think I'm going to drop it and we can bring it in a separate branch later if we want to.
</blockquote></details>

Yeah actually this brings up a feature I was planning on doing but haven't yet... A config that times out jobs. This is common for these kinds of services, where after some config, lets say 60 seconds after all clients disconnect from a job it will terminate the job.

To do this we'll need to wrap `add_action()`'s `watch::Receiver<Arc<ActionState>`  with a wrapper that if dropped will notify the scheduler that a client disconnected, so it can start a counter if it was the last one to connect.

___
___
*[`cas/grpc_service/execution_server.rs` line 224 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KGyWWAyv7wXz32lmn:-N_Ol5Az36RN7dk2tpAg:bh79oki) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L224)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Think that falls down with the GrpcScheduler, right?
</blockquote></details>

I don't think so. If this is a problem in `GrpcScheduler` it'll just need to do an `instance_name` -> `instance_name` mapping.

We need to make the name of the operation contain the instance name. Something like:

```
{intance_name}/{action_info_hash}
```


<!-- Sent from Reviewable.io -->

2023-07-15 22:08 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 224 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KGyWWAyv7wXz32lmn:-N_Qa6eh66EbXRIrRO9-:b5zeitx) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L224)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I don't think so. If this is a problem in `GrpcScheduler` it'll just need to do an `instance_name` -> `instance_name` mapping.

We need to make the name of the operation contain the instance name. Something like:

```
{intance_name}/{action_info_hash}
```
</blockquote></details>

I think #186 will solve much of this.


<!-- Sent from Reviewable.io -->

2023-07-16 14:27 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 21 files reviewed, 2 unresolved discussions (waiting on @allada)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/177#-N_L7BVy4y8ebVUUbCYm:-N_U4i3O0TUD5r_NIEv1:b-fwqmkd) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah actually this brings up a feature I was planning on doing but haven't yet... A config that times out jobs. This is common for these kinds of services, where after some config, lets say 60 seconds after all clients disconnect from a job it will terminate the job.

To do this we'll need to wrap `add_action()`'s `watch::Receiver<Arc<ActionState>`  with a wrapper that if dropped will notify the scheduler that a client disconnected, so it can start a counter if it was the last one to connect.
</blockquote></details>

It will also need to be cancelled on a new `subscribe()`.

___
___
*[`cas/grpc_service/execution_server.rs` line 224 at r3](https://reviewable.io/reviews/allada/turbo-cache/177#-N_KGyWWAyv7wXz32lmn:-N_U4z4o8KkO2A8xKnWJ:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/c91aaa584683906657600811fb99e3257ed00101/cas/grpc_service/execution_server.rs#L224)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think #186 will solve much of this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-16 14:30 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 21 files reviewed, 2 unresolved discussions (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/177#-N_L7BVy4y8ebVUUbCYm:-N_U5lNAAyNbd1KRdnT0:b9m4nye) (no related file):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

It will also need to be cancelled on a new `subscribe()`.
</blockquote></details>

Does it? If we ever get to a point where we a user wants to `subscribe()` and the task happens to be running. We always feed the results of the running job.

___


<!-- Sent from Reviewable.io -->

2023-07-16 14:35 UTC, chrisstaite-menlo commented
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Does it? If we ever get to a point where we a user wants to `subscribe()` and the task happens to be running. We always feed the results of the running job.
</blockquote></details>

This situation:
User starts job and disconnects
Timer started as no connections
User uses WaitExecution to subscribe
Timer fires and kills job being listened to




<!-- Sent from Reviewable.io -->

2023-07-16 14:39 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 21 files reviewed, 2 unresolved discussions (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/177#-N_L7BVy4y8ebVUUbCYm:-N_U7sCA8_SHo1KKjbZa:br5semq) (no related file):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

This situation:
User starts job and disconnects
Timer started as no connections
User uses WaitExecution to subscribe
Timer fires and kills job being listened to
</blockquote></details>

Oh, you mean timer `canceled` on new `subscribe()`... I thought you mean job cancelled on new `subscribe()`. Yeah of course!

___


<!-- Sent from Reviewable.io -->

2023-07-16 14:51 UTC, chrisstaite reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 21 files reviewed, 3 unresolved discussions (waiting on @allada and @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 218 at r7](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UAaUaD143MwkpqvaM:-N_UAaUaD143MwkpqvaN:bmzh769) ([raw file](https://github.com/allada/turbo-cache/blob/a675e662f8f6a281c7618252c162f1f27b36761b/cas/grpc_service/execution_server.rs#L218)):*
> ```XML
>         // the protobuf spec doesn't state that the instance_name can be
>         // retrieved from the path.
>         let mut result_stream = self
> ```

Still needs to get instance_name from ActionInfoHashKey


<!-- Sent from Reviewable.io -->

2023-07-16 16:16 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 1 of 21 files reviewed, 3 unresolved discussions (waiting on @allada, @chrisstaite, and @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 218 at r7](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UAaUaD143MwkpqvaM:-N_UT32Z8QuZxdsY7T4J:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/a675e662f8f6a281c7618252c162f1f27b36761b/cas/grpc_service/execution_server.rs#L218)):*
<details><summary><i>Previously, chrisstaite (Chris) wrote…</i></summary><blockquote>

Still needs to get instance_name from ActionInfoHashKey
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-16 18:24 UTC, chrisstaite-menlo commented
Tested this branch with Goma and it appears to be working.  Still doing the annoying thing where it forgets all the blobs exist on restart (could be because I don't have a Redis running for Goma).

2023-07-16 18:41 UTC, allada requested changes
> Reviewed 4 of 8 files at r7, 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 17 of 21 files reviewed, 10 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 213 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UYODg3yCLWa4cb8Hi:-N_UYODg3yCLWa4cb8Hj:br91r24) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L213)):*
> ```XML
>         request: Request<WaitExecutionRequest>,
>     ) -> Result<Response<ExecuteStream>, Status> {
>         let unique_qualifier = ActionInfoHashKey::try_from(request.into_inner().name.as_str())
> ```

nit:  `&request.into_inner().name` looks better.
___
*[`cas/grpc_service/execution_server.rs` line 215 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UYTvV5ouekURrp-iS:-N_UYTvV5ouekURrp-iT:bk6i5fz) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L215)):*
> ```XML
>         let unique_qualifier = ActionInfoHashKey::try_from(request.into_inner().name.as_str())
>             .err_tip(|| "Decoding operation name into ActionInfoHashKey")?;
>         let Some(instance_info) = self.instance_infos.get(unique_qualifier.instance_name.as_str()) else {
> ```

nit: `&unique_qualifier.instance_name` looks better.
___
*[`cas/grpc_service/execution_server.rs` line 219 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UZDcjCStLmxJZG5Cn:-N_UZDcjCStLmxJZG5Co:bhzfbok) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L219)):*
> ```XML
>         };
>         let Some(rx) = instance_info.scheduler.find_existing_action(&unique_qualifier).await else {
>             return Err(Status::not_found("Failed to find existing task"));
> ```

I wounder if it'd be a good idea to then try and find the item in the action cache before rejecting it?

I don't think the spec says anything about this, but I think it makes sense. From looking at the code, we'd need to modify the scheduler so before it fully drops `ActionResult`, it'll upload it to the CAS (not AC).

No need to do this now, but if you don't want to do it, lets make a TODO. The cool part is that it'll allow users to run an action, go away, and come back later to get the results (assuming the timeout is properly permissive).
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 158 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_Umoj-A6pz_Z9RZanY:-N_UgC7tCRuZh25XjvjI:b-55cxg) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/cache_lookup_scheduler.rs#L158)):*
> ```XML
>         self.cache_check_actions
>             .lock()
>             .insert(action_info.unique_qualifier.clone(), tx.clone());
> ```

There's a bit of a race condition here because we can have two clients at this point trying add the same `unique_qualifier`. This would cause some very bizarre things to happen. We should do a cache lookup here first and feed the existing item if it exists within the same lock.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 181 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UkDCT56V_YznElJCD:-N_UkDCT56V_YznElJCE:b8xymhj) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/cache_lookup_scheduler.rs#L181)):*
> ```XML
>                 Ok(rx) => {
>                     let mut watch_stream = WatchStream::new(rx);
>                     while let Some(action_state) = watch_stream.next().await {
> ```

Hmmm, minor bug here, where we only notify the downstream scheduler that the client has disconnected when the worker sends a notification to the client and `tx.send(action_state).is_err()` triggers an error and drops the `Sender`, which then causes the downstream scheduler to now be able to know the client disconnected.

This currently is not a big problem, since it only causes a very minor amount of additional needless memory, but if/when we implement the ability for the scheduler to timeout tasks because no listeners are active it'll become an issue.

This can be fixed by using a `select!{}` over `tx.closed()` and `watch_stream.next()`. Not sure if we should do this in this PR, but wanted to make sure it was known.

This is a good example on why I think we should try and avoid using spawns as much as possible, granted here we need to use a spawn (unless we change function signatures), this would auto-propagate everything down because the future would get dropped which would call `Drop` on everything downstream.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 208 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UuxH9COBDUbY2jZBx:-N_UuxH9COBDUbY2jZBy:bdu2z6j) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/cache_lookup_scheduler.rs#L208)):*
> ```XML
>                 // re-send it to all receivers.
>                 let rx = tx.subscribe();
>                 let _ = tx.send(current_value.clone());
> ```

I created an upstream ticket for this:
https://github.com/tokio-rs/tokio/issues/5871

Can we make a TODO referencing this ticket?
___
*[`cas/scheduler/simple_scheduler.rs` line 166 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UvdbR6if15-0rySV9:-N_UvdbR6if15-0rySVA:b-q4kpie) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L166)):*
> ```XML
>     // completed while the caller was thinking about calling wait_execution, so
>     // keep their completion state around for a while to send back.
>     recently_completed_actions: Vec<Arc<ActionState>>,
> ```

Can we do this part of the change in a followup PR? I want to think about this one a bit because it plays into both debugging and caching. Also, I'm not sure if the scheduler should do this here or if maybe some kind of logging service might be better to solve this for the debugging case.

We also can probably solve the non-debug use case by doing what is commented on above (store the `ActionResult` in CAS). I am pretty sure buildbarn does this.
___
*[`cas/scheduler/simple_scheduler.rs` line 283 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UwraG2CZAq3eAOkoX:-N_UwraG2CZAq3eAOkoY:b6dyo64) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L283)):*
> ```XML
>     // Gets an existing action by its name, very noddy implementation that just searches for it everywhere.
>     fn find_existing_action(&self, unique_qualifier: &ActionInfoHashKey) -> Option<watch::Receiver<Arc<ActionState>>> {
>         self.queued_actions
> ```

Uug, these values area already indexed by the `ActionInfoHashKey`, but rust's `HashMap` does not support getting it by this value without: https://github.com/rust-lang/rust/issues/56167

It does look like we can use `hashbrown` though to solve it, because it uses `Equivalent<K>` for lookups instead of forcing `K: Borrow<Q>`, but untested:
https://docs.rs/hashbrown/latest/hashbrown/hash_map/struct.HashMap.html#method.get


<!-- Sent from Reviewable.io -->

2023-07-16 18:43 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 17 of 21 files reviewed, 11 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/grpc_scheduler.rs` line 42 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_V-vC171kjd2vfYxBb:-N_V-vC2EhJSMZCGfh7L:b-nu1f9w) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/grpc_scheduler.rs#L42)):*
> ```XML
> impl GrpcScheduler {
>     pub async fn new(config: &config::schedulers::GrpcScheduler) -> Result<Self, Error> {
>         let endpoint = transport::Channel::balance_list(std::iter::once(
> ```

nit: Looks unrelated (possibly future PR?).


<!-- Sent from Reviewable.io -->

2023-07-16 18:50 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 17 of 21 files reviewed, 13 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/grpc_scheduler.rs` line 62 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_V1JNc8UHFA2vRKG_1:-N_V1JNc8UHFA2vRKG_2:bq9ijux) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/grpc_scheduler.rs#L62)):*
> ```XML
>             let (tx, rx) = watch::channel(Arc::new(initial_response.try_into()?));
>             tokio::spawn(async move {
>                 while let Ok(Some(response)) = result_stream.message().await {
> ```

nit: We also need to watch for the `tx.closed()` so we can terminate the grpc stream if our client disconnects.
___
*[`cas/scheduler/grpc_scheduler.rs` line 151 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_V0yv3EtcIV3K_DcDy:-N_V0yv3EtcIV3K_DcDz:bi0bfjw) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/grpc_scheduler.rs#L151)):*
> ```XML
>             .await;
>         if result_stream.is_err() {
>             return None;
> ```

nit: Lets add a `log::info!()` here with the error message.


<!-- Sent from Reviewable.io -->

2023-07-16 18:50 UTC, allada reviewed
> Reviewed 1 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 18 of 21 files reviewed, 13 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)



<!-- Sent from Reviewable.io -->

2023-07-16 18:52 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 18 of 21 files reviewed, 14 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/grpc_scheduler.rs` line 70 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_V1h7-7gUvftmjtx3P:-N_V1h7-7gUvftmjtx3Q:b-nw60ri) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/grpc_scheduler.rs#L70)):*
> ```XML
>                             }
>                         }
>                         Err(err) => log::error!("Error converting response to watch in GrpcScheduler: {}", err),
> ```

nit: 
```
Error converting response to ActionState in GrpcScheduler
```


<!-- Sent from Reviewable.io -->

2023-07-16 19:20 UTC, chrisstaite-menlo reviewed
> Dismissed @allada from a discussion.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 18 of 21 files reviewed, 8 unresolved discussions (waiting on @allada and @chrisstaite)

___
*[`cas/grpc_service/execution_server.rs` line 213 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UYODg3yCLWa4cb8Hi:-N_V2Ho426lN2SXUCfKk:b-db0ooo) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L213)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit:  `&request.into_inner().name` looks better.
</blockquote></details>

`the trait \`From<&String>\` is not implemented for \`ActionInfoHashKey\``
___
*[`cas/grpc_service/execution_server.rs` line 219 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UZDcjCStLmxJZG5Cn:-N_V2aINBRv0-Lbhilu2:b-g7v3gy) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L219)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I wounder if it'd be a good idea to then try and find the item in the action cache before rejecting it?

I don't think the spec says anything about this, but I think it makes sense. From looking at the code, we'd need to modify the scheduler so before it fully drops `ActionResult`, it'll upload it to the CAS (not AC).

No need to do this now, but if you don't want to do it, lets make a TODO. The cool part is that it'll allow users to run an action, go away, and come back later to get the results (assuming the timeout is properly permissive).
</blockquote></details>

Isn't the idea that if you do that you should just look it up in the Action Cache yourself?
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 158 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_Umoj-A6pz_Z9RZanY:-N_V4Mmh7NyzW363zx_3:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/cache_lookup_scheduler.rs#L158)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

There's a bit of a race condition here because we can have two clients at this point trying add the same `unique_qualifier`. This would cause some very bizarre things to happen. We should do a cache lookup here first and feed the existing item if it exists within the same lock.
</blockquote></details>

Done.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 181 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UkDCT56V_YznElJCD:-N_V58C83T1OGgKuSfGt:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/cache_lookup_scheduler.rs#L181)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmmm, minor bug here, where we only notify the downstream scheduler that the client has disconnected when the worker sends a notification to the client and `tx.send(action_state).is_err()` triggers an error and drops the `Sender`, which then causes the downstream scheduler to now be able to know the client disconnected.

This currently is not a big problem, since it only causes a very minor amount of additional needless memory, but if/when we implement the ability for the scheduler to timeout tasks because no listeners are active it'll become an issue.

This can be fixed by using a `select!{}` over `tx.closed()` and `watch_stream.next()`. Not sure if we should do this in this PR, but wanted to make sure it was known.

This is a good example on why I think we should try and avoid using spawns as much as possible, granted here we need to use a spawn (unless we change function signatures), this would auto-propagate everything down because the future would get dropped which would call `Drop` on everything downstream.
</blockquote></details>

Done.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 208 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UuxH9COBDUbY2jZBx:-N_V5Vx3-kvHVfWF75Iy:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/cache_lookup_scheduler.rs#L208)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I created an upstream ticket for this:
https://github.com/tokio-rs/tokio/issues/5871

Can we make a TODO referencing this ticket?
</blockquote></details>

Done.
___
*[`cas/scheduler/grpc_scheduler.rs` line 42 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_V-vC171kjd2vfYxBb:-N_V5XBt5ec05p9Olzis:b-g73dxo) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/grpc_scheduler.rs#L42)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Looks unrelated (possibly future PR?).
</blockquote></details>

This made more sense when I was adding in the `OperationsClient` too, but now I've taken that out it makes a little less sense, but I think this is worth adding in as I believe the `balance_list` will re-try a failed connection whereas the existing code won't.  Happy to move this out to another PR, but it's a bit mixed in now...
___
*[`cas/scheduler/simple_scheduler.rs` line 166 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UvdbR6if15-0rySV9:-N_V7TW3CZwWJZMw7fWJ:bocdzpj) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L166)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we do this part of the change in a followup PR? I want to think about this one a bit because it plays into both debugging and caching. Also, I'm not sure if the scheduler should do this here or if maybe some kind of logging service might be better to solve this for the debugging case.

We also can probably solve the non-debug use case by doing what is commented on above (store the `ActionResult` in CAS). I am pretty sure buildbarn does this.
</blockquote></details>

For fast build actions this is required for Goma otherwise the action disappears between it calling `add_action` and calling `wait_execution`.  That's why I had to implement it.  We could pull it out, but both are necessary for this code to work, so it doesn't make much sense to I don't think?


<!-- Sent from Reviewable.io -->

2023-07-16 19:24 UTC, chrisstaite-menlo commented
*[`cas/scheduler/simple_scheduler.rs` line 283 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UwraG2CZAq3eAOkoX:-N_V98DV2IW9cGFEmMwZ:b-8z4ig3) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L283)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Uug, these values area already indexed by the `ActionInfoHashKey`, but rust's `HashMap` does not support getting it by this value without: https://github.com/rust-lang/rust/issues/56167

It does look like we can use `hashbrown` though to solve it, because it uses `Equivalent<K>` for lookups instead of forcing `K: Borrow<Q>`, but untested:
https://docs.rs/hashbrown/latest/hashbrown/hash_map/struct.HashMap.html#method.get
</blockquote></details>

Looking at the source of `HashSet` it calls `self.base.get` where `base` is `hashbrown`...


<!-- Sent from Reviewable.io -->

2023-07-16 19:32 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 14 of 22 files reviewed, 8 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/grpc_service/execution_server.rs` line 213 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UYODg3yCLWa4cb8Hi:-N_V8wvq2C_oAita4too:b-b0sw51) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L213)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

`the trait \`From<&String>\` is not implemented for \`ActionInfoHashKey\``
</blockquote></details>

blah. Probably needs `Borrow<&T>` magic in the `TryFrom` trait.
___
*[`cas/grpc_service/execution_server.rs` line 219 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UZDcjCStLmxJZG5Cn:-N_V971v1caO_JSVBHX4:b-583sb4) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L219)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Isn't the idea that if you do that you should just look it up in the Action Cache yourself?
</blockquote></details>

Yes and no. If caching was enabled 100% of the time yes, but in our case we can send requests that will not be saved in action cache. In the event the `no_cache` flag is sent on the initial request, by design the `ActionInfoHashKey` will be different for every request, but if the `no_cache` is not set, then it may use the same `ActionInfoHashKey` and thus the same Operation Id.

Lets not get caught up on this in this PR and if possible lets split off this part into a different PR. I will look into how other projects do this. I do remember buildbarn having a flag somewhere saying something like: `Store action results for non-cachable items in the CAS. This breaks the "HASH(value) -> value" guarantee though`.


<!-- Sent from Reviewable.io -->

2023-07-16 19:36 UTC, allada requested changes
> Reviewed 3 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 16 of 25 files reviewed, 5 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/grpc_scheduler.rs` line 42 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_V-vC171kjd2vfYxBb:-N_VBkLl3PRr-mb8Wg7A:bxi96rd) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/grpc_scheduler.rs#L42)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

This made more sense when I was adding in the `OperationsClient` too, but now I've taken that out it makes a little less sense, but I think this is worth adding in as I believe the `balance_list` will re-try a failed connection whereas the existing code won't.  Happy to move this out to another PR, but it's a bit mixed in now...
</blockquote></details>

Yeah, I agree we should use `balance_list`, but we need to modify the config file too, which is technically a breaking change, so it needs to be documented in the commit title.


<!-- Sent from Reviewable.io -->

2023-07-16 19:37 UTC, chrisstaite-menlo commented
*[`cas/scheduler/grpc_scheduler.rs` line 42 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_V-vC171kjd2vfYxBb:-N_VCCUV9f0IYJeW5tkO:b-f9p2xq) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/grpc_scheduler.rs#L42)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah, I agree we should use `balance_list`, but we need to modify the config file too, which is technically a breaking change, so it needs to be documented in the commit title.
</blockquote></details>

Not at all, I just add a single endpoint to the `balance_list` as shown here...


<!-- Sent from Reviewable.io -->

2023-07-16 19:39 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 16 of 25 files reviewed, 5 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/simple_scheduler.rs` line 166 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UvdbR6if15-0rySV9:-N_VCY4FAcLCUFs4oQJk:b50sdj8) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L166)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

For fast build actions this is required for Goma otherwise the action disappears between it calling `add_action` and calling `wait_execution`.  That's why I had to implement it.  We could pull it out, but both are necessary for this code to work, so it doesn't make much sense to I don't think?
</blockquote></details>

I dont want to block this PR on this especially since you are able to get Goma working. So I created a ticket:
https://github.com/allada/turbo-cache/issues/192

Can you just make a note in the code referencing this ticket here?

Something like:
```
// TOOD(#192) Revisit if this is the best way to handle recently completed actions.
```


<!-- Sent from Reviewable.io -->

2023-07-16 19:41 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 16 of 25 files reviewed, 5 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/simple_scheduler.rs` line 283 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UwraG2CZAq3eAOkoX:-N_VD0C_EA54kBx9VZJF:bwsywq9) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L283)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Looking at the source of `HashSet` it calls `self.base.get` where `base` is `hashbrown`...
</blockquote></details>

Can we add a comment here with something like:
```
// TODO: We can lookup the action without needing to iterate the maps but there's no API for it.
// Maybe when: https://github.com/rust-lang/rust/issues/56167 is done?
```


<!-- Sent from Reviewable.io -->

2023-07-16 19:41 UTC, chrisstaite-menlo commented
*[`cas/grpc_service/execution_server.rs` line 219 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UZDcjCStLmxJZG5Cn:-N_VDITH-q9Oh0-3jQ_t:b8w7k9o) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L219)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yes and no. If caching was enabled 100% of the time yes, but in our case we can send requests that will not be saved in action cache. In the event the `no_cache` flag is sent on the initial request, by design the `ActionInfoHashKey` will be different for every request, but if the `no_cache` is not set, then it may use the same `ActionInfoHashKey` and thus the same Operation Id.

Lets not get caught up on this in this PR and if possible lets split off this part into a different PR. I will look into how other projects do this. I do remember buildbarn having a flag somewhere saying something like: `Store action results for non-cachable items in the CAS. This breaks the "HASH(value) -> value" guarantee though`.
</blockquote></details>

Worth a new issue?


<!-- Sent from Reviewable.io -->

2023-07-16 19:42 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 16 of 25 files reviewed, 4 unresolved discussions (waiting on @allada and @chrisstaite)

___
*[`cas/grpc_service/execution_server.rs` line 213 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UYODg3yCLWa4cb8Hi:-N_VDCuZEP2tqLPbLaI7:b-9ygzv0) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/grpc_service/execution_server.rs#L213)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

blah. Probably needs `Borrow<&T>` magic in the `TryFrom` trait.
</blockquote></details>

Did some messing and Googling and found there's not a nice way to do this...
___
*[`cas/scheduler/simple_scheduler.rs` line 166 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UvdbR6if15-0rySV9:-N_VDBet6csn3Ejg-6sC:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L166)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I dont want to block this PR on this especially since you are able to get Goma working. So I created a ticket:
https://github.com/allada/turbo-cache/issues/192

Can you just make a note in the code referencing this ticket here?

Something like:
```
// TOOD(#192) Revisit if this is the best way to handle recently completed actions.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-16 19:43 UTC, chrisstaite-menlo commented
*[`cas/scheduler/simple_scheduler.rs` line 283 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UwraG2CZAq3eAOkoX:-N_VDVwO7MdiLW0iE-rA:b-tzo4nb) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L283)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we add a comment here with something like:
```
// TODO: We can lookup the action without needing to iterate the maps but there's no API for it.
// Maybe when: https://github.com/rust-lang/rust/issues/56167 is done?
```
</blockquote></details>

I already swapped to `hashbrown`.  Do you think I should put it back with an issue?


<!-- Sent from Reviewable.io -->

2023-07-16 19:51 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 16 of 25 files reviewed, 4 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/simple_scheduler.rs` line 283 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UwraG2CZAq3eAOkoX:-N_VEAuC9-PFx-KnQB0r:bgpes69) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L283)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I already swapped to `hashbrown`.  Do you think I should put it back with an issue?
</blockquote></details>

Wait, it was really that easy!?!?!
___
*[`cas/scheduler/simple_scheduler.rs` line 168 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VEOKp2rQh_B03HG2t:-N_VEOKp2rQh_B03HG2u:b4wc3p1) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L168)):*
> ```XML
>     // keep their completion state around for a while to send back.
>     // TODO(#192) Revisit if this is the best way to handle recently completed actions.
>     recently_completed_actions: Vec<Arc<ActionState>>,
> ```

Can't this be a `HashSet` now so we can just grab it without iterating the vector?
___
*[`cas/scheduler/simple_scheduler.rs` line 255 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VFGIB0Oa6pNaAShzp:-N_VFGIB0Oa6pNaAShzq:b-yloju4) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L255)):*
> ```XML
>         self.recently_completed_actions.retain(|action| match &action.stage {
>             ActionStage::Completed(state) => {
>                 if state.execution_metadata.worker_completed_timestamp > expiry_time {
> ```

I think we should wrap `ActionStage` so we can store the timestamp because I don't think we should blindly trust workers and I think we should hold on to non `ActionStage::Completed` (like errors) for some set duration too.


<!-- Sent from Reviewable.io -->

2023-07-16 19:52 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 16 of 25 files reviewed, 5 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/simple_scheduler.rs` line 252 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VF_XJ6L97x_p-NCup:-N_VF_XJ6L97x_p-NCuq:b-6yqjvr) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L252)):*
> ```XML
>     fn clean_recently_completed_actions(&mut self) {
>         // Keep for a minute maximum.
>         let expiry_time = SystemTime::now().checked_sub(Duration::new(60, 0)).unwrap();
> ```

Can we move this setting to a config?


<!-- Sent from Reviewable.io -->

2023-07-16 19:52 UTC, chrisstaite-menlo commented
*[`cas/scheduler/simple_scheduler.rs` line 283 at r8](https://reviewable.io/reviews/allada/turbo-cache/177#-N_UwraG2CZAq3eAOkoX:-N_VFbFG43wEyEm-mr59:b-sikik1) ([raw file](https://github.com/allada/turbo-cache/blob/f4643203fd95df4d3a40d88a231c83a08fd1d491/cas/scheduler/simple_scheduler.rs#L283)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Wait, it was really that easy!?!?!
</blockquote></details>

Seemingly?


<!-- Sent from Reviewable.io -->

2023-07-16 19:53 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 16 of 25 files reviewed, 7 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/simple_scheduler.rs` line 280 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VFpeg8lDFas2A5zHc:-N_VFpehE_KpiUnxLrvV:bio3o3b) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L280)):*
> ```XML
> 
>         // Clean up the actions list.
>         self.clean_recently_completed_actions();
> ```

lets not do this here, we'll do it similar to how we deal with `remove_timedout_workers()`.
___
*[`cas/scheduler/simple_scheduler.rs` line 521 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VFyze-n-glcnVp14-:-N_VFyze-n-glcnVp140:bio3o3b) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L521)):*
> ```XML
>                 .push(running_action.action.current_state);
>             // Clean up any old actions.
>             self.clean_recently_completed_actions();
> ```

lets not do this here, we'll do it similar to how we deal with `remove_timedout_workers()`.


<!-- Sent from Reviewable.io -->

2023-07-16 19:57 UTC, chrisstaite-menlo commented
*[`cas/scheduler/simple_scheduler.rs` line 168 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VEOKp2rQh_B03HG2t:-N_VGpPM4ub6FaWJrwlv:b-ja6l4h) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L168)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can't this be a `HashSet` now so we can just grab it without iterating the vector?
</blockquote></details>

No, because it's `ActionState` not `ActionInfo` :(. I suppose we could update `ActionState` to also be hashed in the same way as `ActionInfo`...


<!-- Sent from Reviewable.io -->

2023-07-16 19:59 UTC, allada requested changes
> Reviewed 2 of 8 files at r7, 2 of 5 files at r9, 4 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 23 of 25 files reviewed, 7 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/simple_scheduler.rs` line 516 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VH6wo6hwPEF6eE0JF:-N_VH6wo6hwPEF6eE0JG:b-iw1q2g) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L516)):*
> ```XML
>             self.active_actions.insert(action_info, running_action);
>             return Ok(());
>         } else if send_result.is_err() {
> ```

shouldn't we add the item to `recently_complted_actions` regardless of if the result was unable to be sent? Ie: there may be multiple clients listening, the first client was success, but the second client then calls `WaitExecution` and fails because the task was multiplexed.


<!-- Sent from Reviewable.io -->

2023-07-16 20:00 UTC, allada reviewed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 24 of 25 files reviewed, 7 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)



<!-- Sent from Reviewable.io -->

2023-07-16 20:02 UTC, allada reviewed
Sorry about doing this in phases. It was a pretty difficult one to review. I finished going over everything. The things commented on are the only things left. Before it was: "I can't really review this until the last comment is addressed".

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177#-:-N_VHW5_AorYlcKFRVJt:b-i1b1cs)* status: 24 of 25 files reviewed, 7 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)



<!-- Sent from Reviewable.io -->

2023-07-16 20:03 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 24 of 25 files reviewed, 7 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/simple_scheduler.rs` line 168 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VEOKp2rQh_B03HG2t:-N_VI6LN-N5K9djmMQGC:b8xgss2) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L168)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

No, because it's `ActionState` not `ActionInfo` :(. I suppose we could update `ActionState` to also be hashed in the same way as `ActionInfo`...
</blockquote></details>

Yeah actually it can. `ActionState` just needs the same hash function that `ActionInfo` has. Ironically `ActionState` is owns the properties that `ActionInfo` uses to hash.


<!-- Sent from Reviewable.io -->

2023-07-16 20:30 UTC, chrisstaite-menlo reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177)* status: 16 of 26 files reviewed, 7 unresolved discussions (waiting on @allada and @chrisstaite)

___
*[`cas/scheduler/simple_scheduler.rs` line 168 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VEOKp2rQh_B03HG2t:-N_VOPow5M1T1mUOvTj7:baq8zuh) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L168)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah actually it can. `ActionState` just needs the same hash function that `ActionInfo` has. Ironically `ActionState` is owns the properties that `ActionInfo` uses to hash.
</blockquote></details>

I actually did this in a different way since I was wrapping the completed time in anyway and implemented it for `CompletedAction`...
___
*[`cas/scheduler/simple_scheduler.rs` line 252 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VF_XJ6L97x_p-NCup:-N_VOIOW37XVrGFEM-CL:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L252)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we move this setting to a config?
</blockquote></details>

Done.
___
*[`cas/scheduler/simple_scheduler.rs` line 255 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VFGIB0Oa6pNaAShzp:-N_VOIcz2lf0Sc7UVLwi:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L255)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think we should wrap `ActionStage` so we can store the timestamp because I don't think we should blindly trust workers and I think we should hold on to non `ActionStage::Completed` (like errors) for some set duration too.
</blockquote></details>

Done.
___
*[`cas/scheduler/simple_scheduler.rs` line 280 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VFpeg8lDFas2A5zHc:-N_VLaot7y2ZQHWPnXsU:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L280)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets not do this here, we'll do it similar to how we deal with `remove_timedout_workers()`.
</blockquote></details>

Done.
___
*[`cas/scheduler/simple_scheduler.rs` line 516 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VH6wo6hwPEF6eE0JF:-N_VL_Xe1lyYVXZW-5dP:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L516)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

shouldn't we add the item to `recently_complted_actions` regardless of if the result was unable to be sent? Ie: there may be multiple clients listening, the first client was success, but the second client then calls `WaitExecution` and fails because the task was multiplexed.
</blockquote></details>

Done.
___
*[`cas/scheduler/simple_scheduler.rs` line 521 at r12](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VFyze-n-glcnVp14-:-N_VLZl-4KgcBLxsRi4x:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/0cbd85d0ec37c175c7d37734f8b0ef4e2b9ad5cb/cas/scheduler/simple_scheduler.rs#L521)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

lets not do this here, we'll do it similar to how we deal with `remove_timedout_workers()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-16 20:31 UTC, chrisstaite-menlo commented
I knew it was going to be a horrid one, because it really should have been more than one PR, but it was a mangled mess!





<!-- Sent from Reviewable.io -->

2023-07-16 21:01 UTC, allada approved these changes
Woot! This was a tough one.

<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>  

> Reviewed 1 of 3 files at r5, 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/177#-:-N_VVUD00LYUJGC_dKwr:bbk9ny)* status: all files reviewed, 2 unresolved discussions (waiting on @chrisstaite and @chrisstaite-menlo)

___
*[`cas/scheduler/default_scheduler_factory.rs` line 70 at r13](https://reviewable.io/reviews/allada/turbo-cache/177#-N_VSz3x6JuC5wrKmOZj:-N_VSz3x6JuC5wrKmOZk:bru9cky) ([raw file](https://github.com/allada/turbo-cache/blob/436642db80f7073a80718bceda3a7421b51bcb6f/cas/scheduler/default_scheduler_factory.rs#L70)):*
> ```XML
> fn start_cleanup_timer(action_scheduler: &Arc<dyn ActionScheduler>) {
>     let weak_scheduler = Arc::downgrade(action_scheduler);
>     tokio::spawn(async move {
> ```

:frowning_face:  It looks like it's time for a `SchedulerManager` so we don't need these spawns to be running all over the place.

No action needed.


<!-- Sent from Reviewable.io -->

2023-07-17 07:52 UTC, merged