Streams may now be resumed on disconnect
allada/turbo-cache pull request #220
Opened 2023-07-23 02:46 UTC by allada

On high latency network connections it is possible that streams will be dropped from time to time. This allows us to now resume from where the upload stream was dropped.

2023-07-23 03:00 UTC, allada reviewed
+@chrisstaite-menlo In my head this seemed way simpler, but then when I got to codding it I kept hitting edge cases, so I ended up making a some support structs to help.

Sadly it is not easy to move those to a new file (I tried) because there's circular reference issues.

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/220#-:-Na-fbXEA4PPy3xJTdq3:b-mgavo4)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)



<!-- Sent from Reviewable.io -->

2023-07-24 16:11 UTC, chrisstaite-menlo requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/220)* status: all files reviewed, 9 unresolved discussions (waiting on @allada)

___
*[`cas/grpc_service/bytestream_server.rs` line 75 at r1](https://reviewable.io/reviews/allada/turbo-cache/220#-Na7eFiL7fRkN-s4cDRy:-Na7eFiL7fRkN-s4cDRz:b3o8uew) ([raw file](https://github.com/allada/turbo-cache/blob/d45cd5802c162b2d95478ef86420cc47b3625a57/cas/grpc_service/bytestream_server.rs#L75)):*
> ```XML
>     /// Consumes the guard and returns the inner state. The stream will be considered
>     /// "finished", will remove it from the active_uploads.
>     fn forget(mut self) -> (DropCloserWriteHalf, StoreUpdateFuture) {
> ```

Not sure about the naming here, `client_closed` or `finished` seems better since `forget` implies not calling `Drop` which is not the case.
___
*[`cas/grpc_service/bytestream_server.rs` line 94 at r1](https://reviewable.io/reviews/allada/turbo-cache/220#-Na7ZFLx9l-_oZMLasSf:-Na7ZFLx9l-_oZMLasSg:bmxtijq) ([raw file](https://github.com/allada/turbo-cache/blob/d45cd5802c162b2d95478ef86420cc47b3625a57/cas/grpc_service/bytestream_server.rs#L94)):*
> ```XML
>             return;
>         };
>         let self_fn = self.sleep_fn.clone();
> ```

This is an odd name, `sleep_fn` makes more sense, no?
___
*[`cas/grpc_service/bytestream_server.rs` line 359 at r1](https://reviewable.io/reviews/allada/turbo-cache/220#-Na7bVF1E4zOlMf2g8j6:-Na7bVF1E4zOlMf2g8j7:b-zgagvu) ([raw file](https://github.com/allada/turbo-cache/blob/d45cd5802c162b2d95478ef86420cc47b3625a57/cas/grpc_service/bytestream_server.rs#L359)):*
> ```XML
>             .err_tip(|| "Invalid digest input in ByteStream::write")?;
>         let mut active_stream_guard = self.create_or_join_upload_stream(uuid, store, digest)?;
>         // let active_stream = active_stream_guard.stream_state.as_mut().unwrap();
> ```

Commented out code
___
*[`cas/grpc_service/bytestream_server.rs` line 427 at r1](https://reviewable.io/reviews/allada/turbo-cache/220#-Na7eY7K1mOvBvw71S-2:-Na7eY7K1mOvBvw71S-3:bo8wo9x) ([raw file](https://github.com/allada/turbo-cache/blob/d45cd5802c162b2d95478ef86420cc47b3625a57/cas/grpc_service/bytestream_server.rs#L427)):*
> ```XML
> 
>         // Close our guard and consider the stream no longer active.
>         drop(active_stream_guard.forget());
> ```

No need for the explicit `drop` here...


<!-- Sent from Reviewable.io -->

2023-07-25 10:16 UTC, chrisstaite-menlo approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/220)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2023-07-26 15:07 UTC, chrisstaite-menlo approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/220)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2023-07-27 07:55 UTC, chrisstaite-menlo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/220#-:-NaLL9hQAd1qtd1WdAQN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)



<!-- Sent from Reviewable.io -->

2023-07-27 15:08 UTC, merged