Fix potential race condition if worker disconnects
allada/turbo-cache pull request #266
Opened 2023-09-10 23:50 UTC by allada

In the event the worker disconnects from the scheduler, we now wait until all actions are killed before we attempt to reconnect to the scheduler. This prevents a race condition where the scheduler does not know about an action the worker is doing resulting in a potential of the scheduler sending the same action to the worker that it has not cleaned up yet.

fixes #246

2023-09-10 23:50 UTC, allada reviewed
+@chrisstaite-menlo 

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/266#-:-Ne0VFQZ37mqYq44YBKH:b96vhr1)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @chrisstaite-menlo)



<!-- Sent from Reviewable.io -->

2023-09-11 07:58 UTC, chrisstaite-menlo requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/266)* status: all files reviewed, 3 unresolved discussions (waiting on @allada)

___
*[`cas/worker/local_worker.rs` line 487 at r1](https://reviewable.io/reviews/allada/turbo-cache/266#-Ne2Dv7I-jz2H4wmrzJp:-Ne2Dv7I-jz2H4wmrzJq:b-lelivx) ([raw file](https://github.com/allada/turbo-cache/blob/1de293f77aa29bc8776adb58e5d0f2a6cea71737/cas/worker/local_worker.rs#L487)):*
> ```XML
>                         (sleep_fn_pin)(Duration::from_secs_f32(sleep_duration)).await;
>                     }
>                     if inner.actions_in_transit.load(Ordering::Acquire) != 0 {
> ```

Might be a good use for a label to perform a for-else rather than check the value again.
___
*[`cas/worker/running_actions_manager.rs` line 1164 at r1](https://reviewable.io/reviews/allada/turbo-cache/266#-Ne2ELRp-A_qp5nyz5dF:-Ne2ELRp-A_qp5nyz5dG:bt2m68v) ([raw file](https://github.com/allada/turbo-cache/blob/1de293f77aa29bc8776adb58e5d0f2a6cea71737/cas/worker/running_actions_manager.rs#L1164)):*
> ```XML
> 
>     fn cleanup_action(&self, action_id: &ActionId) -> Result<(), Error> {
>         println!("cleanup_action triggered");
> ```

Debug value
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 140 at r1](https://reviewable.io/reviews/allada/turbo-cache/266#-Ne2EhOq9ZM0UmVZlsFJ:-Ne2EhOq9ZM0UmVZlsFK:b6d8yq7) ([raw file](https://github.com/allada/turbo-cache/blob/1de293f77aa29bc8776adb58e5d0f2a6cea71737/cas/worker/tests/running_actions_manager_test.rs#L140)):*
> ```XML
> #[cfg(test)]
> mod running_actions_manager_tests {
>     use std::sync::atomic::AtomicBool;
> ```

Weird to place this in the `mod`?


<!-- Sent from Reviewable.io -->

2023-09-11 14:35 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/266)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`cas/worker/local_worker.rs` line 487 at r1](https://reviewable.io/reviews/allada/turbo-cache/266#-Ne2Dv7I-jz2H4wmrzJp:-Ne3epBK-2xSiaAa0eJW:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/1de293f77aa29bc8776adb58e5d0f2a6cea71737/cas/worker/local_worker.rs#L487)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Might be a good use for a label to perform a for-else rather than check the value again.
</blockquote></details>

Done.
___
*[`cas/worker/running_actions_manager.rs` line 1164 at r1](https://reviewable.io/reviews/allada/turbo-cache/266#-Ne2ELRp-A_qp5nyz5dF:-Ne3bTXm4_K1JFYgd9XQ:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/1de293f77aa29bc8776adb58e5d0f2a6cea71737/cas/worker/running_actions_manager.rs#L1164)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Debug value
</blockquote></details>

Done.
___
*[`cas/worker/tests/running_actions_manager_test.rs` line 140 at r1](https://reviewable.io/reviews/allada/turbo-cache/266#-Ne2EhOq9ZM0UmVZlsFJ:-Ne3bbqcEtH0lPF1IDuA:b-mkov3d) ([raw file](https://github.com/allada/turbo-cache/blob/1de293f77aa29bc8776adb58e5d0f2a6cea71737/cas/worker/tests/running_actions_manager_test.rs#L140)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Weird to place this in the `mod`?
</blockquote></details>

Done. My editor did this.


<!-- Sent from Reviewable.io -->

2023-09-11 15:03 UTC, chrisstaite-menlo reviewed
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/266)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @allada)

___
*[`cas/worker/tests/running_actions_manager_test.rs` line 140 at r1](https://reviewable.io/reviews/allada/turbo-cache/266#-Ne2EhOq9ZM0UmVZlsFJ:-Ne3lDBf2GkTlLtwTL8g:b-utdva3) ([raw file](https://github.com/allada/turbo-cache/blob/1de293f77aa29bc8776adb58e5d0f2a6cea71737/cas/worker/tests/running_actions_manager_test.rs#L140)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Done. My editor did this.
</blockquote></details>

Mine did the same for somewhere else. They're so helpful... sometimes.


<!-- Sent from Reviewable.io -->

2023-09-11 15:22 UTC, chrisstaite-menlo approved these changes
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @allada)



<!-- Sent from Reviewable.io -->

2023-09-11 19:51 UTC, merged